#
# TrustedInfrastructure Paths
# The vcenter trusted_infrastructure package provides services that enable a Trusted Infrastructure. They are responsible for ensuring that infrastructure nodes are running trusted software and for releasing encryption keys only to trusted infrastructure nodes.
# Contact: powercli@vmware.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.DESCRIPTION

The ConsumerPrincipals.FilterSpec structure contains data which identifies a connection profile on the trusted vCenter.

.PARAMETER Id
The unqiue identifier of a connection profile. If unset, no filtration will be performed by ID. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: com.vmware.esx.authentication.clientprofile. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: com.vmware.esx.authentication.clientprofile.
.PARAMETER Principals
The principal used by the vCenter to retrieve tokens. If unset, no filtration will be performed by principals.
.PARAMETER Issuer
The service which created and signed the security token. If unset, no filtration will be performed by issuer. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: com.vmware.esx.authentication.trust.security-token-issuer. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: com.vmware.esx.authentication.trust.security-token-issuer.
.OUTPUTS

TrustedInfrastructureTrustAuthorityClustersConsumerPrincipalsFilterSpec<PSCustomObject>

.LINK

Online Version: https://developer.vmware.com/docs/vsphere-automation/latest/vcenter/data-structures/TrustedInfrastructure/TrustAuthorityClusters/ConsumerPrincipals/FilterSpec/
#>

function Initialize-TrustedInfrastructureTrustAuthorityClustersConsumerPrincipalsFilterSpec {
    [CmdletBinding(HelpURI = "https://developer.vmware.com/docs/vsphere-automation/latest/vcenter/data-structures/TrustedInfrastructure/TrustAuthorityClusters/ConsumerPrincipals/FilterSpec/")]
    Param (
        [Parameter(Mandatory = $false)]
        [String[]]
        ${Id},
        [Parameter(Mandatory = $false)]
        [PSCustomObject[]]
        ${Principals},
        [Parameter(Mandatory = $false)]
        [String[]]
        ${Issuer}
    )

    Process {
        'Creating PSCustomObject: VMware.Sdk.vSphere.vCenter.TrustedInfrastructure => vSphereTrustedInfrastructureTrustAuthorityClustersConsumerPrincipalsFilterSpec' | Write-Debug


        $PSO = [PSCustomObject]@{
            "PSTypeName" = "TrustedInfrastructureTrustAuthorityClustersConsumerPrincipalsFilterSpec"
            "id" = ${Id}
            "principals" = ${Principals}
            "issuer" = ${Issuer}
        }


        return $PSO
    }
}

