#
# TrustedInfrastructure Paths
# The vcenter trusted_infrastructure package provides services that enable a Trusted Infrastructure. They are responsible for ensuring that infrastructure nodes are running trusted software and for releasing encryption keys only to trusted infrastructure nodes.
# Contact: powercli@vmware.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.DESCRIPTION

The ClientCertificate.UpdateSpec structure contains fields that describe the client certificate update for a Key Provider.

.PARAMETER Certificate
Public certificate used by every host in the cluster.
.PARAMETER PrivateKey
Private part of the certificate. If unset, the update request is for a public/private client certificate pair, not for a signed CSR.
.OUTPUTS

TrustedInfrastructureTrustAuthorityClustersKmsProvidersClientCertificateUpdateSpec<PSCustomObject>

.LINK

Online Version: https://developer.vmware.com/docs/vsphere-automation/latest/vcenter/data-structures/TrustedInfrastructure/TrustAuthorityClusters/Kms/Providers/ClientCertificate/UpdateSpec/
#>

function Initialize-TrustedInfrastructureTrustAuthorityClustersKmsProvidersClientCertificateUpdateSpec {
    [CmdletBinding(HelpURI = "https://developer.vmware.com/docs/vsphere-automation/latest/vcenter/data-structures/TrustedInfrastructure/TrustAuthorityClusters/Kms/Providers/ClientCertificate/UpdateSpec/")]
    Param (
        [Parameter(Mandatory = $true)]
        [ValidateScript({ $_ -is [string] })]
        ${Certificate},
        [Parameter(Mandatory = $false)]
        [ValidateScript({ $_ -is [string] })]
        ${PrivateKey}
    )

    Process {
        'Creating PSCustomObject: VMware.Sdk.vSphere.vCenter.TrustedInfrastructure => vSphereTrustedInfrastructureTrustAuthorityClustersKmsProvidersClientCertificateUpdateSpec' | Write-Debug


        $PSO = [PSCustomObject]@{
            "PSTypeName" = "TrustedInfrastructureTrustAuthorityClustersKmsProvidersClientCertificateUpdateSpec"
            "certificate" = ${Certificate}
            "private_key" = ${PrivateKey}
        }


        return $PSO
    }
}

