#
# Settings Paths
# The esx settings package provides services to manage ESX settings.
# Contact: powercli@vmware.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.DESCRIPTION

The ComplianceStatus.UpdateSpec structure describes the updates to be made to the compatibility overrides for storage devices in a cluster.

.PARAMETER DeviceReclassifications
List of compatibility overrides to be applied for the storage devices in a cluster.
.OUTPUTS

SettingsClustersSoftwareReportsHardwareCompatibilityStorageDeviceOverridesComplianceStatusUpdateSpec<PSCustomObject>

.LINK

Online Version: https://developer.vmware.com/docs/vsphere-automation/latest/esx/data-structures/Settings/Clusters/Software/Reports/HardwareCompatibility/StorageDeviceOverrides/ComplianceStatus/UpdateSpec/
#>

function Initialize-SettingsClustersSoftwareReportsHardwareCompatibilityStorageDeviceOverridesComplianceStatusUpdateSpec {
    [CmdletBinding(HelpURI = "https://developer.vmware.com/docs/vsphere-automation/latest/esx/data-structures/Settings/Clusters/Software/Reports/HardwareCompatibility/StorageDeviceOverrides/ComplianceStatus/UpdateSpec/")]
    Param (
        [Parameter(Mandatory = $true)]
        [PSCustomObject[]]
        ${DeviceReclassifications}
    )

    Process {
        'Creating PSCustomObject: VMware.Sdk.vSphere.Esx.Settings => vSphereSettingsClustersSoftwareReportsHardwareCompatibilityStorageDeviceOverridesComplianceStatusUpdateSpec' | Write-Debug

        if ($DeviceReclassifications -eq $null) {
            throw "invalid value for 'DeviceReclassifications', 'DeviceReclassifications' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "PSTypeName" = "SettingsClustersSoftwareReportsHardwareCompatibilityStorageDeviceOverridesComplianceStatusUpdateSpec"
            "device_reclassifications" = ${DeviceReclassifications}
        }


        return $PSO
    }
}

